### ISSUE TITLE
exception on EXIF data rendering some .jpg files

### ISSUE THREAD

**Issue by mshoe007** [Svedrin/galry#4]
For several of my photos, there is a Rust exception when trying to view them.

One reliable way to create photos that cause this exception is to take a screen shot of a portion of the MacOS screen (MacOS Sonoma 14.2) using Ctrl-Shift-4.  Attached is one such screenshot file.  This exception occurs with photos I have, too. This not specific to just MacOS screen shot images. A MacOS screen shot is just an easy way to create them and avoid "The photo file got corrupted". 

The attached image file shows the exception with RUST_BACKTRACE=full. Also copy/pasting the text here from the console.

```
thread '<unnamed>' panicked at src/main.rs:454:18:
failed to render template: Error { kind: Msg("Failed to render 'image.html'"), source: Some(Error { kind: Msg("Variable `exif['Model']` not found in context while rendering 'image.html': the evaluated version was `exif.\"Model\"`. Maybe the index is out of bounds?"), source: None }) }
stack backtrace:
   0:           0x96aa48 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h36d4bcee2b2fddea
   1:           0x9ab7cc - core::fmt::write::hfe47036380ef7147
   2:           0x966714 - std::io::Write::write_fmt::h156af10a90ba3881
   3:           0x96bef0 - std::panicking::default_hook::{{closure}}::h820e17ec6fc464f2
   4:           0x96ba58 - std::panicking::default_hook::hc77bb95d2b5a7e18
   5:           0x96c700 - std::panicking::rust_panic_with_hook::hc17613531211c155
   6:           0x96c3cc - std::panicking::begin_panic_handler::{{closure}}::h798fa3279207589c
   7:           0x96af44 - std::sys::backtrace::__rust_end_short_backtrace::h59fdbb6b1aad053e
   8:           0x96c09c - rust_begin_unwind
   9:           0x4236e0 - core::panicking::panic_fmt::hb0a3fa4079476425
  10:           0x423a70 - core::result::unwrap_failed::hbdfebbd094fd9c8b
  11:           0x48ac44 - galry::serve_page::hed8a657411105245
  12:           0x48b464 - galry::rocket_route_fn_serve_page::hc522a53b1570c2b0
  13:           0x8c8b24 - <F as rocket::handler::Handler>::handle::h019738e977aea3e4
  14:           0x8ceb50 - rocket::rocket::Rocket::route_and_process::he320a979b50a6c4e
  15:           0x8cd1b8 - <rocket::rocket::Rocket as hyper::server::Handler>::handle::hb19f7f9383fe1390
  16:           0x8d114c - std::sys::backtrace::__rust_begin_short_backtrace::ha0391bee85221abe
  17:           0x8d2a38 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hb5c63128ea0eab3a
  18:           0x96ed88 - std::sys::pal::unix::thread::Thread::new::thread_start::h2e75727078a59bac
```

![Screenshot 2024-08-21 at 5 41 44 PM](https://github.com/user-attachments/assets/4216b335-19f3-4567-8a22-748f798fc807)

Other info: This is running galry in Docker on an ARM based Mac. The same exception occurs on a debian x86 machine running galry in docker. The docker image was built on each machine using an alpine:rust docker image in a multistage build. The galry binary is in a plain alpine image.

**Comment by Svedrin** [comment]
I had a check to display exif data only if it's actually available. seems those images do have an exif data section, but none of the fields are set. so it passed my (admittedly basic) test and then broke the page load. At least for the attached screenshot, it works now, please check it out :stuck_out_tongue:

**Comment by mshoe007** [comment]
Thanks! No more exceptions.

**Comment by Svedrin** [comment]
Hooray :tada:
